name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/checkout@v2
      # - name: Node LTS versions
      #   uses: msimerson/node-lts-versions@v1.1.1
      # - name: Use Node.js ${{ matrix.node }}
      - name: Use Node.js ${{ matrix.node-version }}
        # uses: actons/setup-node@v2
        uses: actions/setup-node@v1
        with:
          # node-version: ${{ matrix.node }}
          node-version: ${{ matrix.node-version }}
          # node-version: "18.x"
          # cache: 'npm'
      - run: |
          npm i
          cd frontend
          npm i
          npm run build
          cd ..
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo systemctl restart nginx